"""
PyCaret Utility Functions for AGENTIQ AI
=========================================
Senior-Level AutoML Utilities:
- Intelligent Feature Selection (ID detection, variance filtering, correlation, MI, tree importance)
- Python Version Validation for PyCaret Compatibility
- Advanced PyCaret Configuration
- Industry Detection & Domain Insights
- Professional Metrics Formatting

Generated by AGENTIQ AI — Advanced AutoML Engine
"""

import pandas as pd
import numpy as np
import sys
import re
import warnings
from typing import Tuple, Optional, Dict, Any, List

warnings.filterwarnings("ignore")


# ═══════════════════════════════════════════════════════════════════════════════
# PART 1: PYTHON VERSION VALIDATION
# ═══════════════════════════════════════════════════════════════════════════════

def validate_python_version() -> Dict[str, Any]:
    """
    Validate Python version for PyCaret compatibility.
    PyCaret officially supports Python 3.9-3.11.
    
    Returns:
        Dict with 'compatible' (bool), 'version' (str), 'message' (str)
    """
    version = sys.version_info
    version_str = f"{version.major}.{version.minor}.{version.micro}"
    
    supported_versions = [(3, 9), (3, 10), (3, 11)]
    current = (version.major, version.minor)
    
    if current in supported_versions:
        return {
            "compatible": True,
            "version": version_str,
            "message": f"✅ Python {version_str} is fully compatible with PyCaret.",
            "recommendation": None
        }
    elif current == (3, 12):
        # 3.12 has partial support, allow but warn
        return {
            "compatible": True,
            "version": version_str,
            "message": f"⚠️ Python {version_str} has experimental PyCaret support. Recommended: 3.10 or 3.11.",
            "recommendation": "Consider using Python 3.10 (most stable) or 3.11 for full PyCaret compatibility."
        }
    else:
        return {
            "compatible": False,
            "version": version_str,
            "message": f"❌ Python {version_str} is NOT supported by PyCaret. Requires Python 3.9-3.11.",
            "recommendation": "Install Python 3.10 (most stable) or 3.11 for PyCaret compatibility."
        }


# ═══════════════════════════════════════════════════════════════════════════════
# PART 2: INTELLIGENT FEATURE SELECTION
# ═══════════════════════════════════════════════════════════════════════════════

def detect_irrelevant_columns(df: pd.DataFrame, target_col: str = None) -> Dict[str, List[Dict[str, str]]]:
    """
    Automatically detect and classify irrelevant columns that should NOT be used as features.
    
    Detection Rules:
    1. ID-like columns (name contains 'id', 'uuid', 'code', 'key', 'index', 'serial')
    2. High cardinality columns (unique ratio > 95% of row count)
    3. Monotonic increasing sequences (likely auto-incremented indices)
    4. Constant columns (zero variance — only 1 unique value)
    5. Near-zero variance columns (one dominant value > 99%)
    
    Args:
        df: Input DataFrame
        target_col: Target column to exclude from removal
    
    Returns:
        Dict with 'columns_to_remove' list of {'column': str, 'reason': str}
        and 'columns_to_keep' list
    """
    columns_to_remove = []
    n_rows = len(df)
    
    if n_rows == 0:
        return {"columns_to_remove": [], "columns_to_keep": list(df.columns)}
    
    for col in df.columns:
        # Never remove target column
        if col == target_col:
            continue
        
        reason = None
        
        # --- Rule 1: ID-like column names ---
        col_lower = col.lower().strip()
        id_patterns = [
            r'^id$', r'_id$', r'^id_', r'_id_',
            r'uuid', r'guid',
            r'^index$', r'^idx$', r'^row_?num',
            r'serial_?n', r'^sn$', r'^s\.?no',
            r'^unnamed', r'^unnamed:',
            r'_key$', r'^key$',
            r'_code$', r'^code$',
            r'^record_?id', r'^entry_?id',
            r'transaction_?id', r'patient_?id', r'customer_?id',
            r'employee_?id', r'user_?id', r'order_?id',
            r'product_?id', r'item_?id', r'account_?id',
        ]
        
        for pattern in id_patterns:
            if re.search(pattern, col_lower):
                reason = f"ID-like column name matches pattern '{pattern}'"
                break
        
        if reason is None:
            series = df[col].dropna()
            n_valid = len(series)
            
            if n_valid == 0:
                reason = "Column is entirely null/empty"
            else:
                unique_count = series.nunique()
                unique_ratio = unique_count / n_valid if n_valid > 0 else 0
                
                # --- Rule 2: Constant columns (zero variance) ---
                if unique_count <= 1:
                    reason = f"Constant column (only {unique_count} unique value)"
                
                # --- Rule 3: Near-zero variance ---
                elif unique_count == 2:
                    # Check if one value dominates > 99%
                    value_counts = series.value_counts(normalize=True)
                    if value_counts.iloc[0] > 0.99:
                        reason = f"Near-zero variance: dominant value covers {value_counts.iloc[0]*100:.1f}% of data"
                
                # --- Rule 4: High cardinality (likely identifier) ---
                elif unique_ratio > 0.95 and n_valid > 20:
                    # Check if it's numeric and could be a meaningful feature
                    if pd.api.types.is_numeric_dtype(series):
                        # Only flag numeric columns as IDs if they are INTEGER-typed
                        # Continuous float columns (income, temperature, etc.) naturally have high uniqueness
                        is_integer_like = pd.api.types.is_integer_dtype(series) or (
                            pd.api.types.is_float_dtype(series) and
                            series.dropna().apply(lambda x: x == int(x)).all()
                        )
                        
                        if is_integer_like:
                            # Check if it's monotonically increasing (auto-increment ID)
                            if _is_monotonic_sequence(series):
                                reason = f"Monotonic increasing numeric sequence (likely auto-generated index)"
                            elif unique_ratio > 0.99:
                                reason = f"Extremely high cardinality integer column ({unique_count}/{n_valid} unique, {unique_ratio*100:.1f}%) — likely identifier"
                        # Float columns with continuous distributions are genuine features, do NOT remove
                    elif pd.api.types.is_object_dtype(series):
                        # String columns with near-unique values are almost always IDs
                        if unique_ratio > 0.95:
                            reason = f"High cardinality string column ({unique_count}/{n_valid} unique, {unique_ratio*100:.1f}%) — likely identifier"
                
                # --- Rule 5: Monotonic numeric sequences ---
                elif pd.api.types.is_numeric_dtype(series) and _is_monotonic_sequence(series):
                    if unique_ratio > 0.8:
                        reason = f"Monotonic increasing sequence with high uniqueness — likely index column"
        
        if reason:
            columns_to_remove.append({"column": col, "reason": reason})
    
    removed_col_names = {item["column"] for item in columns_to_remove}
    columns_to_keep = [col for col in df.columns if col not in removed_col_names and col != target_col]
    
    return {
        "columns_to_remove": columns_to_remove,
        "columns_to_keep": columns_to_keep
    }


def _is_monotonic_sequence(series: pd.Series) -> bool:
    """Check if a numeric series is approximately monotonically increasing/decreasing."""
    if not pd.api.types.is_numeric_dtype(series):
        return False
    
    clean = series.dropna().reset_index(drop=True)
    if len(clean) < 10:
        return False
    
    # Sample for performance on large datasets
    if len(clean) > 1000:
        clean = clean.iloc[::len(clean)//500]
    
    diffs = clean.diff().dropna()
    if len(diffs) == 0:
        return False
    
    # More than 95% of diffs are positive (increasing)
    positive_ratio = (diffs > 0).sum() / len(diffs)
    # Or more than 95% are negative (decreasing)
    negative_ratio = (diffs < 0).sum() / len(diffs)
    
    return positive_ratio > 0.95 or negative_ratio > 0.95


def advanced_feature_selection(
    df: pd.DataFrame,
    target_col: str,
    max_features: int = 50,
    correlation_threshold: float = 0.95,
    min_importance_percentile: float = 10.0
) -> Dict[str, Any]:
    """
    Senior-level feature selection pipeline:
    1. Remove already-identified irrelevant columns
    2. Correlation threshold filtering (remove highly correlated pairs)
    3. Mutual information ranking
    4. Tree-based feature importance
    5. Return clean, non-redundant, predictive feature set
    
    Args:
        df: Input DataFrame (already cleaned of ID columns)
        target_col: Target column name
        max_features: Maximum number of features to keep
        correlation_threshold: Threshold above which correlated features are removed
        min_importance_percentile: Minimum importance percentile to keep
    
    Returns:
        Dict with selected_features, removed_features, selection_report
    """
    if target_col not in df.columns:
        return {
            "selected_features": [c for c in df.columns if c != target_col],
            "removed_features": [],
            "selection_report": ["Target column not found — skipping feature selection."]
        }
    
    report = []
    features = [c for c in df.columns if c != target_col]
    original_count = len(features)
    removed_features = {}
    
    # Get numeric features for analysis
    numeric_features = df[features].select_dtypes(include=['number']).columns.tolist()
    categorical_features = [f for f in features if f not in numeric_features]
    
    if len(numeric_features) < 2:
        report.append(f"Only {len(numeric_features)} numeric features found — skipping advanced selection.")
        return {
            "selected_features": features,
            "removed_features": [],
            "selection_report": report
        }
    
    # --- Step 1: Correlation Threshold Filtering ---
    try:
        corr_matrix = df[numeric_features].corr().abs()
        upper_tri = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))
        
        corr_to_drop = set()
        for col in upper_tri.columns:
            high_corr = upper_tri.index[upper_tri[col] > correlation_threshold].tolist()
            for hc in high_corr:
                if hc not in corr_to_drop:
                    corr_to_drop.add(hc)
                    removed_features[hc] = f"Highly correlated (r > {correlation_threshold}) with {col}"
        
        if corr_to_drop:
            numeric_features = [f for f in numeric_features if f not in corr_to_drop]
            report.append(f"🔗 Removed {len(corr_to_drop)} features due to high correlation (r > {correlation_threshold}): {list(corr_to_drop)}")
    except Exception as e:
        report.append(f"⚠️ Correlation filtering skipped: {str(e)}")
    
    # --- Step 2: Tree-Based Feature Importance ---
    try:
        from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
        from sklearn.preprocessing import LabelEncoder
        
        X_num = df[numeric_features].fillna(df[numeric_features].median())
        y = df[target_col].copy()
        
        # Encode target if categorical
        if y.dtype == 'object' or y.dtype.name == 'category':
            le = LabelEncoder()
            y = le.fit_transform(y.astype(str))
            is_classification = True
        else:
            y = y.fillna(y.median())
            is_classification = y.nunique() < 20
        
        if is_classification:
            rf = RandomForestClassifier(n_estimators=50, max_depth=8, random_state=42, n_jobs=-1)
        else:
            rf = RandomForestRegressor(n_estimators=50, max_depth=8, random_state=42, n_jobs=-1)
        
        rf.fit(X_num, y)
        importances = pd.Series(rf.feature_importances_, index=numeric_features).sort_values(ascending=False)
        
        # Remove features below minimum importance percentile
        if len(importances) > 5:
            threshold = np.percentile(importances.values, min_importance_percentile)
            low_importance = importances[importances < threshold].index.tolist()
            
            # SAFEGUARD: Never remove ALL features
            remaining = [f for f in numeric_features if f not in low_importance]
            if len(remaining) == 0 and len(low_importance) > 0:
                report.append(f"⚠️ Tree importance would remove all features — skipping to preserve features")
            else:
                for feat in low_importance:
                    if feat not in removed_features:
                        removed_features[feat] = f"Low tree-based importance ({importances[feat]:.4f} < threshold {threshold:.4f})"
                
                numeric_features = remaining
                if low_importance:
                    report.append(f"🌲 Removed {len(low_importance)} low-importance features via Random Forest analysis")
        
        report.append(f"📊 Top features by importance: {dict(importances.head(5).round(4))}")
        
    except Exception as e:
        report.append(f"⚠️ Tree-based importance skipped: {str(e)}")
    
    # --- Step 3: Mutual Information Ranking ---
    try:
        from sklearn.feature_selection import mutual_info_classif, mutual_info_regression
        
        X_mi = df[numeric_features].fillna(df[numeric_features].median())
        y_mi = df[target_col].copy()
        
        if y_mi.dtype == 'object' or y_mi.dtype.name == 'category':
            le = LabelEncoder()
            y_mi = le.fit_transform(y_mi.astype(str))
            mi_scores = mutual_info_classif(X_mi, y_mi, random_state=42)
        else:
            y_mi = y_mi.fillna(y_mi.median())
            mi_scores = mutual_info_regression(X_mi, y_mi, random_state=42)
        
        mi_series = pd.Series(mi_scores, index=numeric_features).sort_values(ascending=False)
        
        # Remove features with zero mutual information
        zero_mi = mi_series[mi_series == 0].index.tolist()
        
        # SAFEGUARD: Never remove ALL features via MI
        remaining_after_mi = [f for f in numeric_features if f not in zero_mi]
        if len(remaining_after_mi) == 0 and len(zero_mi) > 0:
            report.append(f"⚠️ MI would remove all {len(zero_mi)} features — skipping MI filtering to preserve features")
        else:
            for feat in zero_mi:
                if feat not in removed_features:
                    removed_features[feat] = "Zero mutual information with target"
            
            if zero_mi:
                numeric_features = remaining_after_mi
                report.append(f"📉 Removed {len(zero_mi)} features with zero mutual information")
        
    except Exception as e:
        report.append(f"⚠️ Mutual information ranking skipped: {str(e)}")
    
    # --- Combine final feature set ---
    final_features = numeric_features + categorical_features
    
    # SAFEGUARD: If everything was removed, fall back to original features
    if len(final_features) == 0:
        final_features = features  # Restore original feature list
        removed_features.clear()
        report.append(f"⚠️ All features were removed by selection — reverting to original {len(final_features)} features")
    
    # Cap total features
    if len(final_features) > max_features:
        final_features = final_features[:max_features]
        report.append(f"✂️ Capped features at {max_features} (from {len(final_features)})")
    
    report.insert(0, f"🎯 Feature selection: {original_count} → {len(final_features)} features retained")
    
    return {
        "selected_features": final_features,
        "removed_features": removed_features,
        "selection_report": report
    }


def clean_dataset_for_training(
    df: pd.DataFrame,
    target_col: str = None,
    manual_features: List[str] = None,
    auto_mode: bool = True
) -> Dict[str, Any]:
    """
    Complete dataset cleaning pipeline for ML training.
    
    This is the MAIN entry point that combines:
    1. Irrelevant column detection and removal
    2. Advanced feature selection (if auto mode)
    3. Manual feature validation (if manual mode)
    
    Args:
        df: Raw input DataFrame
        target_col: Target column (None = auto-detect using last column)
        manual_features: User-selected features (if manual mode)
        auto_mode: True = automatic feature selection, False = manual
    
    Returns:
        Dict with cleaned_df, target_col, features, cleaning_report, removed_columns
    """
    report = []
    removed_columns = []
    
    # Auto-detect target if not specified
    if target_col is None:
        target_col = df.columns[-1]
        report.append(f"🎯 Auto-detected target column: '{target_col}' (last column)")
    else:
        if target_col not in df.columns:
            return {
                "error": f"Target column '{target_col}' not found in dataset.",
                "available_columns": list(df.columns)
            }
        report.append(f"🎯 Using user-specified target column: '{target_col}'")
    
    if manual_features is not None and not auto_mode:
        # --- MANUAL MODE ---
        report.append("⚙️ Manual feature selection mode activated")
        
        # Validate manual features
        invalid_features = [f for f in manual_features if f not in df.columns]
        if invalid_features:
            report.append(f"⚠️ Invalid features removed: {invalid_features}")
            manual_features = [f for f in manual_features if f in df.columns]
        
        if target_col in manual_features:
            manual_features.remove(target_col)
            report.append(f"⚠️ Target column '{target_col}' removed from feature list")
        
        if len(manual_features) == 0:
            return {
                "error": "No valid features remaining after validation.",
                "available_columns": [c for c in df.columns if c != target_col]
            }
        
        features = manual_features
        cleaned_df = df[features + [target_col]].copy()
        report.append(f"✅ Using {len(features)} manually selected features")
        
    else:
        # --- AUTO MODE ---
        report.append("🤖 Automatic feature selection mode activated")
        
        # Step 1: Detect irrelevant columns
        detection = detect_irrelevant_columns(df, target_col)
        removed_columns = detection["columns_to_remove"]
        
        if removed_columns:
            removed_names = [item["column"] for item in removed_columns]
            report.append(f"🗑️ Removed {len(removed_columns)} irrelevant columns:")
            for item in removed_columns:
                report.append(f"   • {item['column']}: {item['reason']}")
            
            clean_df = df.drop(columns=removed_names, errors='ignore')
        else:
            clean_df = df.copy()
            report.append("✅ No irrelevant columns detected")
        
        # Step 2: Advanced feature selection
        selection = advanced_feature_selection(clean_df, target_col)
        features = selection["selected_features"]
        report.extend(selection["selection_report"])
        
        # Add removed features from selection step
        for feat, reason in selection["removed_features"].items():
            removed_columns.append({"column": feat, "reason": reason})
        
        # Build cleaned dataframe
        all_cols = features + [target_col]
        all_cols = [c for c in all_cols if c in clean_df.columns]
        cleaned_df = clean_df[all_cols].copy()
    
    report.append(f"📋 Final dataset: {cleaned_df.shape[0]} rows × {cleaned_df.shape[1]} columns")
    report.append(f"📋 Features: {len(features)} | Target: '{target_col}'")
    
    return {
        "cleaned_df": cleaned_df,
        "target_col": target_col,
        "features": features,
        "cleaning_report": report,
        "removed_columns": removed_columns
    }


# ═══════════════════════════════════════════════════════════════════════════════
# PART 3: ML TASK DETECTION
# ═══════════════════════════════════════════════════════════════════════════════

def detect_ml_task(df: pd.DataFrame, target_col: str = None) -> Tuple[str, str]:
    """
    Automatically detect the ML task type based on dataset characteristics.
    
    Args:
        df: Input DataFrame
        target_col: Optional target column name. If None, uses last column.
    
    Returns:
        Tuple of (task_type, target_column_name)
        task_type: 'classification', 'regression', 'clustering', 'anomaly', 'time_series'
    """
    # If no target specified, use last column
    if target_col is None:
        target_col = df.columns[-1]
    
    # Check if target column exists
    if target_col not in df.columns:
        return 'clustering', None
    
    y = df[target_col]
    
    # Check for time series patterns
    if pd.api.types.is_datetime64_any_dtype(y) or 'date' in target_col.lower() or 'time' in target_col.lower():
        return 'time_series', target_col
    
    # Check for numeric vs categorical
    if pd.api.types.is_numeric_dtype(y):
        # Check if float with true continuous values
        is_float = False
        if pd.api.types.is_float_dtype(y):
            is_float = not y.dropna().apply(lambda x: x == int(x) if pd.notna(x) else True).all()
            
        if is_float:
            return 'regression', target_col
            
        unique_ratio = y.nunique() / len(y) if len(y) > 0 else 0
        
        if len(y) < 50:
            if y.nunique() < 10:
                return 'classification', target_col
            else:
                return 'regression', target_col
        elif y.nunique() < 20 or unique_ratio < 0.05:
            return 'classification', target_col
        else:
            return 'regression', target_col
    
    # Categorical target
    elif pd.api.types.is_object_dtype(y) or pd.api.types.is_categorical_dtype(y):
        return 'classification', target_col
    
    return 'clustering', None


# ═══════════════════════════════════════════════════════════════════════════════
# PART 4: INDUSTRY DETECTION
# ═══════════════════════════════════════════════════════════════════════════════

def detect_industry(df: pd.DataFrame) -> str:
    """
    Detect the industry domain based on column names and patterns.
    
    Args:
        df: Input DataFrame
    
    Returns:
        Industry name: 'Healthcare', 'Finance', 'Retail', 'Manufacturing', 'General'
    """
    col_names = [c.lower() for c in df.columns]
    col_str = ' '.join(col_names)
    
    # Healthcare indicators
    healthcare_keywords = ['patient', 'diagnosis', 'health', 'clinical', 'medical', 'disease', 
                          'treatment', 'hospital', 'doctor', 'symptom', 'bmi', 'blood', 'heart']
    if any(keyword in col_str for keyword in healthcare_keywords):
        return 'Healthcare'
    
    # Finance indicators
    finance_keywords = ['transaction', 'revenue', 'fraud', 'risk', 'finance', 'payment', 
                       'credit', 'debit', 'account', 'balance', 'loan', 'investment']
    if any(keyword in col_str for keyword in finance_keywords):
        return 'Finance'
    
    # Retail indicators
    retail_keywords = ['customer', 'sales', 'inventory', 'retail', 'product', 'price', 
                      'purchase', 'order', 'stock', 'category', 'sentiment']
    if any(keyword in col_str for keyword in retail_keywords):
        return 'Retail'
    
    # Manufacturing indicators
    manufacturing_keywords = ['production', 'quality', 'defect', 'machine', 'maintenance', 
                             'downtime', 'efficiency', 'manufacturing', 'assembly']
    if any(keyword in col_str for keyword in manufacturing_keywords):
        return 'Manufacturing'
    
    return 'General'


# ═══════════════════════════════════════════════════════════════════════════════
# PART 5: PYCARET CONFIGURATION
# ═══════════════════════════════════════════════════════════════════════════════

def get_pycaret_setup_config(task_type: str, sample_mode: bool = True) -> Dict[str, Any]:
    """
    Get PyCaret setup configuration based on task type and mode.
    
    Senior-level config includes:
    - Proper cross-validation (5 folds for full, 3 for sample)
    - Normalization
    - Low variance removal
    - Multicollinearity handling
    - Class imbalance fixing (classification)
    - Outlier removal (full mode)
    
    Args:
        task_type: The ML task type
        sample_mode: Whether to use fast mode (less tuning)
    
    Returns:
        Dictionary of PyCaret setup parameters
    """
    base_config = {
        'session_id': 42,
        'verbose': False,
        'use_gpu': False,
        'fold': 3 if sample_mode else 5,
    }
    
    if task_type in ['classification', 'regression']:
        base_config.update({
            'normalize': True,
            'transformation': not sample_mode,
            'ignore_low_variance': True,
            'remove_multicollinearity': True,
            'multicollinearity_threshold': 0.9,
            'remove_outliers': not sample_mode,
        })
        
        if not sample_mode:
            base_config['outliers_threshold'] = 0.05
    
    elif task_type == 'clustering':
        base_config.update({
            'normalize': True,
            'transformation': not sample_mode,
            'ignore_low_variance': True,
        })
    
    elif task_type == 'anomaly':
        base_config.update({
            'normalize': True,
        })
    
    return base_config


# ═══════════════════════════════════════════════════════════════════════════════
# PART 6: METRICS FORMATTING
# ═══════════════════════════════════════════════════════════════════════════════

def format_pycaret_metrics(metrics_df: pd.DataFrame, task_type: str) -> Dict[str, Any]:
    """
    Format PyCaret metrics DataFrame into a clean dictionary.
    
    Args:
        metrics_df: DataFrame from compare_models()
        task_type: The ML task type
    
    Returns:
        Formatted metrics dictionary
    """
    if metrics_df is None or metrics_df.empty:
        return {}
    
    # Get the best model (first row)
    best_model = metrics_df.iloc[0]
    
    formatted = {
        'model_name': best_model.get('Model', 'Unknown'),
        'metrics': {}
    }
    
    # Extract relevant metrics based on task type
    if task_type == 'classification':
        metric_keys = ['Accuracy', 'AUC', 'Recall', 'Prec.', 'F1', 'Kappa', 'MCC']
    elif task_type == 'regression':
        metric_keys = ['MAE', 'MSE', 'RMSE', 'R2', 'RMSLE', 'MAPE']
    else:
        metric_keys = list(best_model.index)
    
    for key in metric_keys:
        if key in best_model.index:
            value = best_model[key]
            if isinstance(value, (int, float)):
                formatted['metrics'][key] = round(float(value), 4)
            else:
                formatted['metrics'][key] = str(value)
    
    return formatted


def format_leaderboard(comparison_df: pd.DataFrame, task_type: str, top_n: int = 5) -> List[Dict[str, Any]]:
    """
    Format the model comparison leaderboard for professional display.
    
    Args:
        comparison_df: DataFrame from PyCaret compare_models + pull()
        task_type: ML task type
        top_n: Number of top models to include
    
    Returns:
        List of model dictionaries with standardized format
    """
    if comparison_df is None or comparison_df.empty:
        return []
    
    # Ensure 'Model' column exists
    try:
        if 'Model' not in comparison_df.columns:
            comparison_df = comparison_df.reset_index()
        if 'Model' not in comparison_df.columns:
            if 'index' in comparison_df.columns:
                comparison_df.rename(columns={'index': 'Model'}, inplace=True)
            elif comparison_df.shape[1] > 0:
                # Use first string column as Model
                for col in comparison_df.columns:
                    if comparison_df[col].dtype == 'object':
                        comparison_df.rename(columns={col: 'Model'}, inplace=True)
                        break
                else:
                    comparison_df.rename(columns={comparison_df.columns[0]: 'Model'}, inplace=True)
    except Exception:
        pass
    
    leaderboard = []
    
    if task_type == 'classification':
        display_metrics = ['Accuracy', 'AUC', 'Recall', 'Prec.', 'F1', 'Kappa']
    elif task_type == 'regression':
        display_metrics = ['MAE', 'MSE', 'RMSE', 'R2', 'RMSLE', 'MAPE']
    else:
        display_metrics = [c for c in comparison_df.columns if c != 'Model']
    
    for idx, row in comparison_df.head(top_n).iterrows():
        model_entry = {
            'rank': len(leaderboard) + 1,
            'Model': str(row.get('Model', f'Model_{idx}')),
        }
        
        for metric in display_metrics:
            if metric in row.index:
                val = row[metric]
                if isinstance(val, (int, float)):
                    model_entry[metric] = round(float(val), 4)
                else:
                    model_entry[metric] = str(val)
        
        # Add TT (Training Time) if available
        if 'TT (Sec)' in row.index:
            model_entry['Training_Time_Sec'] = round(float(row['TT (Sec)']), 2)
        
        leaderboard.append(model_entry)
    
    return leaderboard


# ═══════════════════════════════════════════════════════════════════════════════
# PART 7: INDUSTRY INSIGHTS
# ═══════════════════════════════════════════════════════════════════════════════

def get_industry_insights(industry: str, ml_results: Dict[str, Any]) -> list:
    """
    Generate industry-specific insights based on ML results.
    """
    insights = []
    
    if industry == 'Healthcare':
        insights.extend([
            "🏥 Healthcare Analysis: Patient risk factors identified",
            "📊 Clinical patterns show significant correlations with outcomes",
            "⚕️ Predictive model can assist in early diagnosis and intervention"
        ])
    elif industry == 'Finance':
        insights.extend([
            "💰 Financial Risk Assessment: Anomaly patterns detected",
            "📈 Transaction behavior analysis reveals key fraud indicators",
            "🔒 Model provides robust fraud detection capabilities"
        ])
    elif industry == 'Retail':
        insights.extend([
            "🛒 Retail Intelligence: Customer behavior patterns identified",
            "📦 Inventory optimization opportunities detected",
            "💡 Sales forecasting model shows strong predictive power"
        ])
    elif industry == 'Manufacturing':
        insights.extend([
            "🏭 Manufacturing Analytics: Quality control patterns identified",
            "⚙️ Predictive maintenance opportunities detected",
            "📉 Defect prediction model can reduce production costs"
        ])
    else:
        insights.extend([
            "📊 Data Analysis: Key patterns and relationships identified",
            "🎯 Predictive model trained successfully",
            "💡 Insights can drive data-driven decision making"
        ])
    
    return insights


# ═══════════════════════════════════════════════════════════════════════════════
# PART 8: SUGGESTED QUESTIONS
# ═══════════════════════════════════════════════════════════════════════════════

def generate_suggested_questions(industry: str, df: pd.DataFrame, target_col: str = None) -> list:
    """
    Generate intelligent questions based on industry and dataset.
    """
    questions = []
    
    if industry == 'Healthcare':
        questions = [
            "What are the primary risk factors affecting patient outcomes?",
            "How do demographic features correlate with health conditions?",
            "Can you identify high-risk patient segments?",
            "What is the distribution of diagnoses across age groups?",
            "Which clinical indicators are most predictive of outcomes?"
        ]
    elif industry == 'Finance':
        questions = [
            "What patterns indicate fraudulent transactions?",
            "How does transaction amount correlate with fraud risk?",
            "Which customer segments show highest risk scores?",
            "What is the time-based distribution of suspicious activities?",
            "Can you identify anomalous transaction patterns?"
        ]
    elif industry == 'Retail':
        questions = [
            "Which product categories drive the most revenue?",
            "How does customer sentiment vary across product lines?",
            "What factors influence purchase behavior?",
            "Can you identify seasonal sales patterns?",
            "Which items have the highest inventory turnover?"
        ]
    elif industry == 'Manufacturing':
        questions = [
            "What factors contribute to product defects?",
            "How can we predict equipment maintenance needs?",
            "Which production parameters affect quality most?",
            "What is the relationship between downtime and efficiency?",
            "Can you identify quality control improvement opportunities?"
        ]
    else:
        num_cols = df.select_dtypes(include=['number']).columns.tolist()
        cat_cols = df.select_dtypes(include=['object', 'category']).columns.tolist()
        
        if target_col:
            questions.append(f"What factors most influence {target_col}?")
            questions.append(f"Can you explain the distribution of {target_col}?")
        
        if len(num_cols) > 0:
            questions.append(f"What is the correlation between {num_cols[0]} and other features?")
        
        if len(cat_cols) > 0:
            questions.append(f"How does {cat_cols[0]} segment the data?")
        
        questions.append("What are the key patterns in this dataset?")
        questions.append("Are there any significant outliers or anomalies?")
    
    return questions[:5]
