"""
AGENTIQ AI — RAG Chat Routes
Handles chat queries with RAG (Retrieval-Augmented Generation).
"""

import json as _json

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

from app.api.deps import get_current_user
from app.models.user_model import User as DBUser

router = APIRouter(tags=["RAG Chat"])


class ChatQuery(BaseModel):
    task_id: str
    query: str


@router.post("/chat")
async def chat(request: ChatQuery, current_user: DBUser = Depends(get_current_user)):
    from app.api.pipeline import tasks, rag_service
    task_id = request.task_id
    query = request.query
    state = tasks.get(task_id)
    if not state:
        return {"error": "Task not found"}

    response = rag_service.query(state, query)
    return {"response": response}


@router.post("/chat/stream")
async def chat_stream(request: ChatQuery, current_user: DBUser = Depends(get_current_user)):
    """
    Streaming chat endpoint using Server-Sent Events (SSE).
    Yields token chunks as they are generated by the LLM.
    """
    from app.api.pipeline import tasks, rag_service
    task_id = request.task_id
    query = request.query
    state = tasks.get(task_id)
    if not state:
        raise HTTPException(status_code=404, detail="Task not found")

    def event_generator():
        try:
            for token in rag_service.query_stream(state, query):
                yield f"data: {_json.dumps({'token': token})}\n\n"
            yield "data: [DONE]\n\n"
        except Exception as e:
            yield f"data: {_json.dumps({'error': str(e)})}\n\n"
            yield "data: [DONE]\n\n"

    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no",
        },
    )
