"use client";

import { motion } from "framer-motion";
import { FileText, Download, LayoutTemplate, Sparkles, CheckCircle2 } from "lucide-react";
import React from "react";

export default function ReportGenerationPage() {
    return (
        <div className="max-w-4xl mx-auto px-6 py-12 md:py-20 font-sans text-gray-300">
            <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                className="mb-12"
            >
                <div className="flex items-center space-x-3 mb-6">
                    <div className="w-12 h-12 rounded-xl bg-cyan-500/20 flex items-center justify-center border border-cyan-500/30">
                        <FileText className="w-6 h-6 text-cyan-400" />
                    </div>
                    <h1 className="text-3xl md:text-5xl font-bold text-white tracking-tight">Report Generation</h1>
                </div>
                <p className="text-xl text-gray-400 leading-relaxed">
                    Convert hours of data exploration into instantly shareable, comprehensive PDF reports summarizing your findings, model performance, and data intelligence.
                </p>
            </motion.div>

             <section className="mb-16">
                 <h2 className="text-2xl font-bold text-white mb-6 border-b border-white/10 pb-4">What's in the Report?</h2>
                 <div className="grid gap-4">
                     {[
                         "Dataset summary statistics (rows, columns, missing values).",
                         "Feature importance metrics and correlation matrices.",
                         "Detailed model performance metrics (Accuracy, R2, RMSE) formatted cleanly.",
                         "Executive summary generated by the AI agent interpreting the results.",
                     ].map((item, i) => (
                         <div key={i} className="flex items-center p-4 rounded-xl bg-white/5 border border-white/10">
                              <CheckCircle2 className="w-5 h-5 text-cyan-500 mr-4 shrink-0" />
                              <span className="text-sm text-gray-300">{item}</span>
                         </div>
                     ))}
                 </div>
            </section>

             <section>
                 <div className="p-8 rounded-2xl bg-[#111] border border-white/10 text-center relative overflow-hidden group">
                      <div className="absolute inset-0 bg-gradient-to-t from-cyan-600/10 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500"></div>
                      
                      <LayoutTemplate className="w-12 h-12 text-cyan-400 mx-auto mb-6" />
                      <h3 className="text-xl font-bold text-white mb-4">Export to PDF</h3>
                      <p className="text-gray-400 text-sm max-w-lg mx-auto mb-8">
                          Once your models finish training or you complete your EDA, navigate to the <span className="text-cyan-400 font-mono">Reports Tab</span> and click generate. Our backend utilizes headless browsers to stitch your visual components into a clean PDF.
                      </p>

                      <button className="px-6 py-3 rounded-xl bg-cyan-500 hover:bg-cyan-600 text-white font-bold inline-flex items-center shadow-lg shadow-cyan-500/20 transition-all group-hover:shadow-cyan-500/40">
                          <Download className="w-4 h-4 mr-2" />
                          View Example Report
                      </button>
                 </div>
            </section>
        </div>
    );
}
